# syntax=docker/dockerfile:1
ARG TARGETARCH

FROM jenkins/ssh-agent:jdk21 AS base-amd64
ADD https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz /tmp/gcloud.tar.gz

FROM jenkins/ssh-agent:jdk21 AS base-arm64
ADD https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-arm.tar.gz /tmp/gcloud.tar.gz

FROM base-${TARGETARCH} AS final
ARG TARGETARCH

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 \
    && rm -rf /var/lib/apt/lists/*

RUN <<'SETUP'
set -e
# Add Docker's official GPG key:
apt-get update
apt-get install -y ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF

apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
SETUP

RUN <<EOF
set -e
echo "baue für $TARGETARCH"
tar -xzf /tmp/gcloud.tar.gz -C /opt
/opt/google-cloud-sdk/install.sh --quiet --path-update=false
ln -s /opt/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud
rm /tmp/gcloud.tar.gz
EOF
