services:
  db:
    container_name: kanban-db
    image: postgres:18
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
    ports:
      - "15432:5432"
    restart: unless-stopped
    volumes:
      - banking-db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresUser -d db" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  banking-db-data:
