pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('backend') {
                    echo "Building the backend"
                    sh './gradlew clean assemble'
                }
            }
        }
        stage('testing') {
            steps {
                dir('backend') {
                    script {
                        try {
                            echo 'running tests'
                            sh './gradlew test'
                        }
                        catch (err) {
                            unstable(message: "${STAGE_NAME} is unstable")
                        }
                    }
                }
            }
        }
        stage('lint') {
            steps {
                dir('backend') {
                    script {
                        try {
                            echo 'check lint'
                            sh './gradlew ktlintCheck'
                        }
                        catch (err) {
                            unstable(message: "${STAGE_NAME} is unstable")
                        }
                    }
                }
            }
        }
        stage('deploy') {
            when {
                allOf {
                    branch 'main'
                    expression { currentBuild.currentResult == 'SUCCESS' }
                }
            }
            steps {
                echo 'deploying'
                echo 'not implemented yet'
            }
        }
    }
}
